Update README.md
eddiejaoude/eddiehub-hacktoberfest-practice pull request #11
Opened 2022-08-30 07:16 UTC by AryanSharma21

### Related issue

### What changes does this PR do?

### Screenshots (If any)

### Questions

2022-08-31 18:20 UTC, maharshi-sinha approved these changes

2022-09-02 19:08 UTC, maharshi-sinha approved these changes

2022-09-03 06:34 UTC, maharshi-sinha requested changes
Add your name in line number 327 as per alphabetical order rest everything is fine. Also, let me know if you face any kind of problem while contributing.

2023-01-07 11:51 UTC, eddiejaoude commented
This is a fork repo, please make changes to the original repo here https://github.com/EddieHubCommunity/hacktoberfest-practice

I will be deleting this fork to avoid any confusion in the future

2023-01-07 11:51 UTC, closed without merging